### ISSUE TITLE
Training of the saved models.

### ISSUE THREAD

**Issue by rajakrohan** [batikim09/LIVE_SER#3]
I was wondering about the saved models and about their learning, can you explain a bit about model training. It was amazing how the model gave the probability values of valence and arousal in the last layers but there is no public data set with labelled valence and arousal scores to train such model. Please give a insight of how the model is trained that predicts 3 class valence and arousal scores rather than conventional n-class discrete emotions.

**Comment by batikim09** [comment]
We grouped discrete classes, such as happiness, sadness, and etc. into three classes for  arousal and valence. For example, happiness belongs to high arousal and positive valence at the same time. Of course, this is not an ideal method since each corpus may have different interpretations of these discrete classes. However, we just wanted to show the proof of concept (aggregating multiple corpora) and we often find this approach in some previous work.
 
Schuller, Bjorn, et al. "Cross-corpus acoustic emotion recognition: Variances and strategies." IEEE Transactions on Affective Computing 1.2 (2010): 119-131.

Automatic ranking of engagement of a group of children “in the wild” using emotional states and deep pose machines
https://www.researchgate.net/publication/321085662_Automatic_ranking_of_engagement_of_a_group_of_children_in_the_wild_using_emotional_states_and_deep_pose_machines
